"""Build the offline station lookup from Trainline's ODbL-licensed stations.csv."""

import csv
import json
import sys
import unicodedata
from collections import defaultdict
from pathlib import Path


def key(name: str) -> str:
    return (
        "".join(
            char
            for char in unicodedata.normalize("NFD", name)
            if not ("\u0300" <= char <= "\u036f")
        )
        .replace(".", "")
        .strip()
        .upper()
    )


def main(source: Path, destination: Path) -> None:
    candidates = defaultdict(list)
    with source.open(encoding="utf-8-sig", newline="") as file:
        for row in csv.DictReader(file, delimiter=";"):
            if (
                row["is_suggestable"] != "t"
                or not row["name"]
                or not row["latitude"]
                or not row["longitude"]
                or not row["time_zone"]
            ):
                continue
            try:
                lat, lon = float(row["latitude"]), float(row["longitude"])
            except ValueError:
                continue
            if not (-90 <= lat <= 90 and -180 <= lon <= 180):
                continue
            candidates[key(row["name"])].append(
                (row["name"], round(lat, 5), round(lon, 5), row["time_zone"], row["country"])
            )

    stations = {}
    for name, matches in candidates.items():
        if len({match[1:] for match in matches}) == 1:
            label, lat, lon, timezone, _country = matches[0]
            stations[name] = [label, lat, lon, timezone]

    if len(stations) < 50_000:
        raise ValueError(f"Expected at least 50,000 unambiguous stations; found {len(stations)}")

    data = json.dumps(stations, ensure_ascii=False, separators=(",", ":"), sort_keys=True)
    destination.write_text(
        "// Generated by scripts/build-station-gazetteer.py from Trainline EU stations.csv (ODbL 1.0).\n"
        "// See README.md for source and attribution. Ambiguous names are excluded.\n"
        "export const STATIONS: Record<string, [string, number, number, string]> = "
        + data
        + ";\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(stations)} unambiguous places to {destination}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit("Usage: python3 scripts/build-station-gazetteer.py stations.csv src/lib/journal/stations.generated.ts")
    main(Path(sys.argv[1]), Path(sys.argv[2]))
